"use strict";

module.exports = Object.freeze({
  account: Object.freeze({
    username: "demo",
    email: "demo@beekeepr.example",
    password: "replace-me",
  }),

  history: Object.freeze({
    months: 18,
    intervalMinutes: 10,
  }),

  provider: "demo-simulator",

  thresholds: Object.freeze({
    alertsEnabled: true,
    warningLowThreshold: 92,
    warningHighThreshold: 98,
    criticalLowThreshold: 89,
    criticalHighThreshold: 101,
  }),

  locations: Object.freeze([
    Object.freeze({
      key: "wny",
      name: "Western New York Demo Yard",
      cityName: "Buffalo, NY",
      timeZone: "America/New_York",
      lat: 42.8864,
      lon: -78.8784,
      climate: Object.freeze({
        averageTempF: 49,
        seasonalAmplitudeF: 28,
        winterDailyAmplitudeF: 7,
        summerDailyAmplitudeF: 13,
        peakDayOfYear: 201,
        dailyPeakHour: 15.2,
        synopticNoiseF: 5.0,
        shortNoiseF: 1.3,
        humidityBasePct: 70,
        humidityAmplitudePct: 17,
        windBaseMps: 3.6,
        windAmplitudeMps: 1.9,
        pressureBaseHpa: 1014.8,
        broodStartDay: 88,
        broodEndDay: 286,
        heatStressTempF: 86,
        coldStressTempF: 18,
      }),
    }),
    Object.freeze({
      key: "ca",
      name: "California Central Valley Demo Yard",
      cityName: "Davis, CA",
      timeZone: "America/Los_Angeles",
      lat: 38.5449,
      lon: -121.7405,
      climate: Object.freeze({
        averageTempF: 61,
        seasonalAmplitudeF: 24,
        winterDailyAmplitudeF: 9,
        summerDailyAmplitudeF: 17,
        peakDayOfYear: 213,
        dailyPeakHour: 16.4,
        synopticNoiseF: 3.6,
        shortNoiseF: 0.9,
        humidityBasePct: 58,
        humidityAmplitudePct: 12,
        windBaseMps: 2.2,
        windAmplitudeMps: 1.0,
        pressureBaseHpa: 1013.1,
        broodStartDay: 38,
        broodEndDay: 334,
        heatStressTempF: 95,
        coldStressTempF: 35,
      }),
    }),
  ]),

  hives: Object.freeze([
    Object.freeze({
      key: "wny-01",
      locationKey: "wny",
      name: "Lake Erie Stable Hive",
      notes: "Western New York hive with steadier brood temperatures near the lakeshore",
      installedAt: "2024-11-01T13:30:00.000Z",
      deviceInstalledAt: "2024-11-01T13:30:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.1,
        strength: 0.88,
        broodDailyAmplitudeF: 0.28,
        broodSeasonalAmplitudeF: 0.22,
        winterClusterTempF: 91.2,
        winterExternalSensitivity: 0.06,
        activeExternalSensitivity: 0.02,
        sensorPlacementOffsetF: 0.05,
        phaseShiftHours: 0.5,
      }),
      rssi: Object.freeze({
        baselineDbm: -62,
        dailyAmplitudeDb: 6,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "swarm",
          start: "2026-05-09T17:30:00.000Z",
          durationMinutes: 60,
          intensity: 0.68,
          note: "Short spring swarm preparation pulse",
        }),
        Object.freeze({
          type: "weak_signal",
          start: "2025-12-14T11:00:00.000Z",
          durationMinutes: 5760,
          intensity: 0.58,
          note: "Lake-effect snow and icing weaken gateway reception",
        }),
      ]),
    }),
    Object.freeze({
      key: "wny-02",
      locationKey: "wny",
      name: "Niagara Snowbelt Hive",
      notes: "Western New York hive with stronger cold-season pressure and wider swings",
      installedAt: "2024-11-01T13:45:00.000Z",
      deviceInstalledAt: "2024-11-01T13:45:00.000Z",
      internal: Object.freeze({
        baselineTempF: 94.6,
        strength: 0.71,
        broodDailyAmplitudeF: 0.48,
        broodSeasonalAmplitudeF: 0.34,
        winterClusterTempF: 89.7,
        winterExternalSensitivity: 0.11,
        activeExternalSensitivity: 0.03,
        sensorPlacementOffsetF: -0.25,
        phaseShiftHours: 2.2,
      }),
      rssi: Object.freeze({
        baselineDbm: -70,
        dailyAmplitudeDb: 8,
        noiseDb: 3,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "brood_decline",
          start: "2025-06-02T04:00:00.000Z",
          durationMinutes: 30240,
          intensity: 0.55,
          note: "Slow brood decline after a wet late spring",
        }),
        Object.freeze({
          type: "sensor_issue",
          start: "2026-03-06T14:20:00.000Z",
          durationMinutes: 30,
          intensity: 0.9,
          direction: "drop",
          note: "Brief loose-probe drop during a cold snap",
        }),
      ]),
    }),
    Object.freeze({
      key: "ca-01",
      locationKey: "ca",
      name: "Yolo Stable Hive",
      notes: "California Central Valley hive with stable brood heat and dry summer afternoons",
      installedAt: "2024-11-01T16:00:00.000Z",
      deviceInstalledAt: "2024-11-01T16:00:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.8,
        strength: 0.9,
        broodDailyAmplitudeF: 0.34,
        broodSeasonalAmplitudeF: 0.2,
        winterClusterTempF: 92.5,
        winterExternalSensitivity: 0.04,
        activeExternalSensitivity: 0.026,
        sensorPlacementOffsetF: 0.1,
        phaseShiftHours: 0.8,
      }),
      rssi: Object.freeze({
        baselineDbm: -59,
        dailyAmplitudeDb: 5,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "heat_stress",
          start: "2025-07-27T22:30:00.000Z",
          durationMinutes: 420,
          intensity: 0.8,
          note: "Central Valley afternoon heat wave pushes brood high",
        }),
        Object.freeze({
          type: "weak_signal",
          start: "2026-02-10T14:00:00.000Z",
          durationMinutes: 10080,
          intensity: 0.55,
          note: "Foggy mornings and orchard equipment interfere with signal",
        }),
      ]),
    }),
    Object.freeze({
      key: "ca-02",
      locationKey: "ca",
      name: "Delta Orchard Hive",
      notes: "California orchard hive with a mild queen issue and occasional summer heat pressure",
      installedAt: "2024-11-01T16:15:00.000Z",
      deviceInstalledAt: "2024-11-01T16:15:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.3,
        strength: 0.81,
        broodDailyAmplitudeF: 0.4,
        broodSeasonalAmplitudeF: 0.28,
        winterClusterTempF: 91.3,
        winterExternalSensitivity: 0.06,
        activeExternalSensitivity: 0.03,
        sensorPlacementOffsetF: 0.05,
        phaseShiftHours: 1.6,
      }),
      rssi: Object.freeze({
        baselineDbm: -65,
        dailyAmplitudeDb: 7,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "queen_issue",
          start: "2025-08-18T07:00:00.000Z",
          durationMinutes: 20160,
          intensity: 0.68,
          note: "Late-summer brood regulation softens after queen slowdown",
        }),
        Object.freeze({
          type: "heat_stress",
          start: "2026-06-21T22:00:00.000Z",
          durationMinutes: 540,
          intensity: 0.72,
          note: "Future summer heat event for demo tick and backfill",
        }),
      ]),
    }),
    Object.freeze({
      key: "ca-03",
      locationKey: "ca",
      name: "Solano Variable Hive",
      notes: "California hive with wider daily swings and occasional sensor anomalies",
      installedAt: "2024-11-01T16:30:00.000Z",
      deviceInstalledAt: "2024-11-01T16:30:00.000Z",
      internal: Object.freeze({
        baselineTempF: 94.8,
        strength: 0.74,
        broodDailyAmplitudeF: 0.54,
        broodSeasonalAmplitudeF: 0.34,
        winterClusterTempF: 90.9,
        winterExternalSensitivity: 0.08,
        activeExternalSensitivity: 0.034,
        sensorPlacementOffsetF: -0.12,
        phaseShiftHours: 2.4,
      }),
      rssi: Object.freeze({
        baselineDbm: -69,
        dailyAmplitudeDb: 8,
        noiseDb: 3,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "sensor_issue",
          start: "2025-10-10T03:40:00.000Z",
          durationMinutes: 20,
          intensity: 0.8,
          direction: "spike",
          note: "Brief warm spike from a loose probe in dry conditions",
        }),
        Object.freeze({
          type: "brood_decline",
          start: "2025-04-28T07:00:00.000Z",
          durationMinutes: 30240,
          intensity: 0.52,
          note: "Slow spring brood decline during a dearth period",
        }),
      ]),
    }),
  ]),
});
