"use strict";

module.exports = Object.freeze({
  account: Object.freeze({
    username: "demo",
    email: "demo@beekeepr.example",
    password: "replace-me",
  }),

  history: Object.freeze({
    months: 18,
    intervalMinutes: 10,
  }),

  provider: "demo-simulator",

  thresholds: Object.freeze({
    alertsEnabled: true,
    warningLowThreshold: 92,
    warningHighThreshold: 98,
    criticalLowThreshold: 89,
    criticalHighThreshold: 101,
  }),

  locations: Object.freeze([
    Object.freeze({
      key: "roc",
      name: "Rochester, NY Demo Yard",
      cityName: "Rochester, NY",
      timeZone: "America/New_York",
      lat: 43.1566,
      lon: -77.6088,
      climate: Object.freeze({
        averageTempF: 49,
        seasonalAmplitudeF: 29,
        winterDailyAmplitudeF: 7,
        summerDailyAmplitudeF: 13,
        peakDayOfYear: 203,
        dailyPeakHour: 15.5,
        synopticNoiseF: 4.8,
        shortNoiseF: 1.2,
        humidityBasePct: 68,
        humidityAmplitudePct: 16,
        windBaseMps: 3.1,
        windAmplitudeMps: 1.6,
        pressureBaseHpa: 1014.5,
        broodStartDay: 86,
        broodEndDay: 292,
        heatStressTempF: 88,
        coldStressTempF: 22,
      }),
    }),
    Object.freeze({
      key: "atl",
      name: "Atlanta, GA Demo Yard",
      cityName: "Atlanta, GA",
      timeZone: "America/New_York",
      lat: 33.749,
      lon: -84.388,
      climate: Object.freeze({
        averageTempF: 63,
        seasonalAmplitudeF: 22,
        winterDailyAmplitudeF: 8,
        summerDailyAmplitudeF: 12,
        peakDayOfYear: 205,
        dailyPeakHour: 16,
        synopticNoiseF: 4.1,
        shortNoiseF: 1.0,
        humidityBasePct: 64,
        humidityAmplitudePct: 13,
        windBaseMps: 2.6,
        windAmplitudeMps: 1.2,
        pressureBaseHpa: 1012.8,
        broodStartDay: 46,
        broodEndDay: 330,
        heatStressTempF: 92,
        coldStressTempF: 30,
      }),
    }),
  ]),

  hives: Object.freeze([
    Object.freeze({
      key: "roc-01",
      locationKey: "roc",
      name: "Highland Stable Hive",
      notes: "Strong Rochester hive with a stable brood nest profile",
      installedAt: "2024-11-01T13:00:00.000Z",
      deviceInstalledAt: "2024-11-01T13:00:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.1,
        strength: 0.92,
        broodDailyAmplitudeF: 0.25,
        broodSeasonalAmplitudeF: 0.2,
        winterClusterTempF: 91.5,
        winterExternalSensitivity: 0.05,
        activeExternalSensitivity: 0.018,
        sensorPlacementOffsetF: 0,
        phaseShiftHours: 0.2,
      }),
      rssi: Object.freeze({
        baselineDbm: -58,
        dailyAmplitudeDb: 5,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "swarm",
          start: "2026-04-23T17:40:00.000Z",
          durationMinutes: 50,
          intensity: 0.75,
          note: "Brief pre-swarm heat spike",
        }),
        Object.freeze({
          type: "weak_signal",
          start: "2025-12-08T12:00:00.000Z",
          durationMinutes: 4320,
          intensity: 0.55,
          note: "Snow cover and battery sag",
        }),
      ]),
    }),
    Object.freeze({
      key: "roc-02",
      locationKey: "roc",
      name: "Genesee Production Hive",
      notes: "Productive Rochester hive with a mild queen issue scenario",
      installedAt: "2024-11-01T13:15:00.000Z",
      deviceInstalledAt: "2024-11-01T13:15:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.7,
        strength: 0.84,
        broodDailyAmplitudeF: 0.32,
        broodSeasonalAmplitudeF: 0.25,
        winterClusterTempF: 90.8,
        winterExternalSensitivity: 0.07,
        activeExternalSensitivity: 0.022,
        sensorPlacementOffsetF: 0.2,
        phaseShiftHours: 1.1,
      }),
      rssi: Object.freeze({
        baselineDbm: -64,
        dailyAmplitudeDb: 7,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "queen_issue",
          start: "2025-08-11T00:00:00.000Z",
          durationMinutes: 20160,
          intensity: 0.7,
          note: "Reduced brood regulation after queen performance drops",
        }),
        Object.freeze({
          type: "cold_stress",
          start: "2026-01-18T03:00:00.000Z",
          durationMinutes: 480,
          intensity: 0.65,
          note: "Cold overnight cluster stress",
        }),
      ]),
    }),
    Object.freeze({
      key: "roc-03",
      locationKey: "roc",
      name: "Cobbs Hill Cool Hive",
      notes: "Weaker Rochester hive with cooler winter sensor readings",
      installedAt: "2024-11-01T13:30:00.000Z",
      deviceInstalledAt: "2024-11-01T13:30:00.000Z",
      internal: Object.freeze({
        baselineTempF: 94.5,
        strength: 0.66,
        broodDailyAmplitudeF: 0.45,
        broodSeasonalAmplitudeF: 0.36,
        winterClusterTempF: 89.2,
        winterExternalSensitivity: 0.1,
        activeExternalSensitivity: 0.03,
        sensorPlacementOffsetF: -0.4,
        phaseShiftHours: 2,
      }),
      rssi: Object.freeze({
        baselineDbm: -71,
        dailyAmplitudeDb: 8,
        noiseDb: 3,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "brood_decline",
          start: "2025-05-27T00:00:00.000Z",
          durationMinutes: 30240,
          intensity: 0.55,
          note: "Slow spring brood decline",
        }),
        Object.freeze({
          type: "sensor_issue",
          start: "2026-03-02T09:20:00.000Z",
          durationMinutes: 30,
          intensity: 0.9,
          direction: "drop",
          note: "Loose probe creates a brief unrealistic drop",
        }),
      ]),
    }),
    Object.freeze({
      key: "atl-01",
      locationKey: "atl",
      name: "Piedmont Warm Hive",
      notes: "Strong Atlanta hive with summer heat stress scenarios",
      installedAt: "2024-11-01T14:00:00.000Z",
      deviceInstalledAt: "2024-11-01T14:00:00.000Z",
      internal: Object.freeze({
        baselineTempF: 95.9,
        strength: 0.88,
        broodDailyAmplitudeF: 0.36,
        broodSeasonalAmplitudeF: 0.22,
        winterClusterTempF: 92.3,
        winterExternalSensitivity: 0.05,
        activeExternalSensitivity: 0.028,
        sensorPlacementOffsetF: 0.15,
        phaseShiftHours: 0.7,
      }),
      rssi: Object.freeze({
        baselineDbm: -61,
        dailyAmplitudeDb: 6,
        noiseDb: 2,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "heat_stress",
          start: "2025-07-21T16:00:00.000Z",
          durationMinutes: 420,
          intensity: 0.8,
          note: "Afternoon heat wave pushes brood nest high",
        }),
        Object.freeze({
          type: "heat_stress",
          start: "2026-06-18T16:00:00.000Z",
          durationMinutes: 480,
          intensity: 0.75,
          note: "Planned future heat stress for demo tick",
        }),
      ]),
    }),
    Object.freeze({
      key: "atl-02",
      locationKey: "atl",
      name: "Grant Park Variable Hive",
      notes: "Atlanta hive with wider daily swings and signal degradation",
      installedAt: "2024-11-01T14:15:00.000Z",
      deviceInstalledAt: "2024-11-01T14:15:00.000Z",
      internal: Object.freeze({
        baselineTempF: 94.9,
        strength: 0.76,
        broodDailyAmplitudeF: 0.52,
        broodSeasonalAmplitudeF: 0.34,
        winterClusterTempF: 90.6,
        winterExternalSensitivity: 0.08,
        activeExternalSensitivity: 0.032,
        sensorPlacementOffsetF: -0.1,
        phaseShiftHours: 2.3,
      }),
      rssi: Object.freeze({
        baselineDbm: -68,
        dailyAmplitudeDb: 8,
        noiseDb: 3,
      }),
      scenarios: Object.freeze([
        Object.freeze({
          type: "sensor_issue",
          start: "2025-10-04T21:10:00.000Z",
          durationMinutes: 20,
          intensity: 0.8,
          direction: "spike",
          note: "Brief probe fault for anomaly testing",
        }),
        Object.freeze({
          type: "weak_signal",
          start: "2026-02-14T06:00:00.000Z",
          durationMinutes: 10080,
          intensity: 0.7,
          note: "Gateway moved farther from hive",
        }),
      ]),
    }),
  ]),
});
